In [13]:
# This is the panda practice session


In [14]:

%%html
<style type='text/css'>
.CodeMirror{
font-size: 17px;
font-family: Lora;
</style>

In [15]:
import numpy as np
import pandas as pd

In [16]:
# Object Creation
s = pd.Series([1,3,5,np.nan,6,8])

In [18]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [22]:
series = pd.Series([1,3,5])

In [24]:
series

0    1
1    3
2    5
dtype: int64

In [26]:
# Creating a DataFrame by passing a NumPy array, with a datetime index
dates = pd.date_range("20130101", periods=6)

In [27]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [29]:
df = pd.DataFrame(np.random.randn(6,4), index = dates, columns = list('ABCD'))

In [30]:
df

A         B         C         D
2013-01-01  0.289080 -0.365905  0.689123 -0.780208
2013-01-02 -0.766666 -1.067370  2.001799 -0.741881
2013-01-03  0.024032 -0.053726 -1.894078 -0.126489
2013-01-04 -1.508662 -1.527980 -0.537460  0.476969
2013-01-05  0.218242  0.174161 -0.703335 -0.885044
2013-01-06 -0.061164  0.791101 -1.332745 -0.048505

In [33]:
# Checking NumPy which returns an array
okay = np.random.rand(8,5)

In [34]:
okay

array([[0.48180297, 0.64788418, 0.34845307, 0.26782876, 0.21451759],
       [0.0804656 , 0.11320871, 0.30408504, 0.7153916 , 0.65559111],
       [0.32654942, 0.93682817, 0.99681364, 0.53012153, 0.19809998],
       [0.57222325, 0.041704  , 0.05683089, 0.78775897, 0.77861754],
       [0.84046272, 0.538319  , 0.6570597 , 0.26526148, 0.98362462],
       [0.85688712, 0.25267555, 0.36315905, 0.56317312, 0.21476237],
       [0.73335008, 0.31306651, 0.31225698, 0.90143088, 0.9872468 ],
       [0.14849037, 0.5169464 , 0.52526415, 0.83034413, 0.56159294]])

In [43]:
df2 = pd.DataFrame(okay, index = list([1,2,3,4,5,6,7,8]), columns=list("ABCDE"))

 df2

In [45]:
df2

A         B         C         D         E
1  0.481803  0.647884  0.348453  0.267829  0.214518
2  0.080466  0.113209  0.304085  0.715392  0.655591
3  0.326549  0.936828  0.996814  0.530122  0.198100
4  0.572223  0.041704  0.056831  0.787759  0.778618
5  0.840463  0.538319  0.657060  0.265261  0.983625
6  0.856887  0.252676  0.363159  0.563173  0.214762
7  0.733350  0.313067  0.312257  0.901431  0.987247
8  0.148490  0.516946  0.525264  0.830344  0.561593

In [46]:
# List Creation using a string
string1 = list("ABCDEF")

In [48]:
string1   # This splits the elements of the string and creates a list

['A', 'B', 'C', 'D', 'E', 'F']

In [49]:
# Creating a DataFrame by passing a dictionary of objects that can be converted into series like structure

In [61]:
df3 = pd.DataFrame(
{
    "A": 1.0,
    "B": pd.Timestamp("20130102"),
    "C": pd.Series(1, index = list(range(1,12)), dtype = "float32"),
    "D": np.array([3]*11, dtype = "int32"),
    "E": pd.Categorical(['test', 'train', 'test', 'train',"main",'chain','hen','goat','soar','bore','here']),
    "F": "foo",
    
}
)

In [62]:
df3

A          B    C  D      E    F
1   1.0 2013-01-02  1.0  3   test  foo
2   1.0 2013-01-02  1.0  3  train  foo
3   1.0 2013-01-02  1.0  3   test  foo
4   1.0 2013-01-02  1.0  3  train  foo
5   1.0 2013-01-02  1.0  3   main  foo
6   1.0 2013-01-02  1.0  3  chain  foo
7   1.0 2013-01-02  1.0  3    hen  foo
8   1.0 2013-01-02  1.0  3   goat  foo
9   1.0 2013-01-02  1.0  3   soar  foo
10  1.0 2013-01-02  1.0  3   bore  foo
11  1.0 2013-01-02  1.0  3   here  foo

In [63]:
df3.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [64]:
df3.head()

A          B    C  D      E    F
1  1.0 2013-01-02  1.0  3   test  foo
2  1.0 2013-01-02  1.0  3  train  foo
3  1.0 2013-01-02  1.0  3   test  foo
4  1.0 2013-01-02  1.0  3  train  foo
5  1.0 2013-01-02  1.0  3   main  foo

In [66]:
df3.tail()

A          B    C  D     E    F
7   1.0 2013-01-02  1.0  3   hen  foo
8   1.0 2013-01-02  1.0  3  goat  foo
9   1.0 2013-01-02  1.0  3  soar  foo
10  1.0 2013-01-02  1.0  3  bore  foo
11  1.0 2013-01-02  1.0  3  here  foo

In [67]:
df3.head(1)

A          B    C  D     E    F
1  1.0 2013-01-02  1.0  3  test  foo

In [68]:
df3.tail(3)

A          B    C  D     E    F
9   1.0 2013-01-02  1.0  3  soar  foo
10  1.0 2013-01-02  1.0  3  bore  foo
11  1.0 2013-01-02  1.0  3  here  foo

In [69]:
df3.index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64')

In [70]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [71]:
df.to_numpy()

array([[ 0.28907973, -0.36590469,  0.68912306, -0.78020829],
       [-0.7666657 , -1.06737009,  2.00179878, -0.74188076],
       [ 0.02403161, -0.05372572, -1.89407837, -0.12648875],
       [-1.50866232, -1.52798017, -0.53746005,  0.47696891],
       [ 0.21824165,  0.17416143, -0.7033347 , -0.88504352],
       [-0.06116385,  0.79110143, -1.33274547, -0.04850548]])

In [72]:
df3.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'main', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'chain', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'hen', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'goat', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'soar', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'bore', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'here', 'foo']],
      dtype=object)

In [74]:
df.T
# This transposes the data, means it shifts columns to rows and vice-versa

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.289080   -0.766666    0.024032   -1.508662    0.218242   -0.061164
B   -0.365905   -1.067370   -0.053726   -1.527980    0.174161    0.791101
C    0.689123    2.001799   -1.894078   -0.537460   -0.703335   -1.332745
D   -0.780208   -0.741881   -0.126489    0.476969   -0.885044   -0.048505

In [76]:
df.sort_index(axis = 1, ascending=False) 
# Sorting by an axis

D         C         B         A
2013-01-01 -0.780208  0.689123 -0.365905  0.289080
2013-01-02 -0.741881  2.001799 -1.067370 -0.766666
2013-01-03 -0.126489 -1.894078 -0.053726  0.024032
2013-01-04  0.476969 -0.537460 -1.527980 -1.508662
2013-01-05 -0.885044 -0.703335  0.174161  0.218242
2013-01-06 -0.048505 -1.332745  0.791101 -0.061164

In [77]:
df.sort_values(by="B")

A         B         C         D
2013-01-04 -1.508662 -1.527980 -0.537460  0.476969
2013-01-02 -0.766666 -1.067370  2.001799 -0.741881
2013-01-01  0.289080 -0.365905  0.689123 -0.780208
2013-01-03  0.024032 -0.053726 -1.894078 -0.126489
2013-01-05  0.218242  0.174161 -0.703335 -0.885044
2013-01-06 -0.061164  0.791101 -1.332745 -0.048505

In [79]:
# SELECTION

In [81]:
df.A  
#This is equivalent to df['A']

2013-01-01    0.289080
2013-01-02   -0.766666
2013-01-03    0.024032
2013-01-04   -1.508662
2013-01-05    0.218242
2013-01-06   -0.061164
Freq: D, Name: A, dtype: float64

In [82]:
df['A']

2013-01-01    0.289080
2013-01-02   -0.766666
2013-01-03    0.024032
2013-01-04   -1.508662
2013-01-05    0.218242
2013-01-06   -0.061164
Freq: D, Name: A, dtype: float64

In [84]:
#Slicing operation can be performed as well
# Note: This does the slicing of rows, not columns
df[0:3]

A         B         C         D
2013-01-01  0.289080 -0.365905  0.689123 -0.780208
2013-01-02 -0.766666 -1.067370  2.001799 -0.741881
2013-01-03  0.024032 -0.053726 -1.894078 -0.126489

In [86]:
df['20130102': '20130104']
# Slicing using the index name

A         B         C         D
2013-01-02 -0.766666 -1.067370  2.001799 -0.741881
2013-01-03  0.024032 -0.053726 -1.894078 -0.126489
2013-01-04 -1.508662 -1.527980 -0.537460  0.476969

In [88]:
# Selection by using label
# This gives all the data of index o across rows.
df.loc[dates[0]]

A    0.289080
B   -0.365905
C    0.689123
D   -0.780208
Name: 2013-01-01 00:00:00, dtype: float64